[2022-02-03 13:20:37,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_gcs_dag.format_to_parquet_task manual__2022-02-03T13:15:25.753926+00:00 [queued]>
[2022-02-03 13:20:38,008] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_gcs_dag.format_to_parquet_task manual__2022-02-03T13:15:25.753926+00:00 [queued]>
[2022-02-03 13:20:38,009] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 13:20:38,009] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 13:20:38,009] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 13:20:38,032] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-02-03 13:15:25.753926+00:00
[2022-02-03 13:20:38,040] {standard_task_runner.py:52} INFO - Started process 349 to run task
[2022-02-03 13:20:38,050] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_gcs_dag', 'format_to_parquet_task', 'manual__2022-02-03T13:15:25.753926+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/yellow_taxi_gcs_dag.py', '--cfg-path', '/tmp/tmp3ljydxn6', '--error-file', '/tmp/tmpdswvnov6']
[2022-02-03 13:20:38,052] {standard_task_runner.py:77} INFO - Job 10: Subtask format_to_parquet_task
[2022-02-03 13:20:38,172] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_gcs_dag.format_to_parquet_task manual__2022-02-03T13:15:25.753926+00:00 [running]> on host 2b92176b720f
[2022-02-03 13:20:38,322] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-03T13:15:25.753926+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-03T13:15:25.753926+00:00
[2022-02-03 13:20:38,336] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_taxi_gcs_dag.py", line 29, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/yellow_tripdata_2019-01.csv'. Detail: [errno 2] No such file or directory
[2022-02-03 13:20:38,363] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_gcs_dag, task_id=format_to_parquet_task, execution_date=20220203T131525, start_date=20220203T132037, end_date=20220203T132038
[2022-02-03 13:20:38,405] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_taxi_gcs_dag.py", line 29, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/yellow_tripdata_2019-01.csv'. Detail: [errno 2] No such file or directory
[2022-02-03 13:20:38,465] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-03 13:20:38,543] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
