[2022-02-03 18:14:14,150] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-03 18:14:14,176] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-03 18:14:14,176] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:14:14,176] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 18:14:14,177] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:14:14,204] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 00:00:00+00:00
[2022-02-03 18:14:14,211] {standard_task_runner.py:52} INFO - Started process 869 to run task
[2022-02-03 18:14:14,217] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-03-02T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmp9w18fa8v', '--error-file', '/tmp/tmpkij6_48b']
[2022-02-03 18:14:14,229] {standard_task_runner.py:77} INFO - Job 154: Subtask download_dataset_task
[2022-02-03 18:14:14,358] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [running]> on host bd2f56b76e32
[2022-02-03 18:14:14,485] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 18:14:14,551] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T00:00:00+00:00
[2022-02-03 18:14:14,552] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-03 18:14:14,553] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/output_2019-03.csv']
[2022-02-03 18:14:14,569] {subprocess.py:85} INFO - Output:
[2022-02-03 18:14:26,375] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-03 18:14:26,411] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190302T000000, start_date=20220203T181414, end_date=20220203T181426
[2022-02-03 18:14:26,440] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 18:14:26,491] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
<<<<<<< HEAD
[2022-02-23 19:08:26,768] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 19:08:26,791] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 19:08:26,792] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:08:26,792] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 19:08:26,792] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:08:26,815] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 00:00:00+00:00
[2022-02-23 19:08:26,827] {standard_task_runner.py:52} INFO - Started process 119 to run task
[2022-02-23 19:08:26,833] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-03-02T00:00:00+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpqngaeziq', '--error-file', '/tmp/tmp_bxqg3gv']
[2022-02-23 19:08:26,835] {standard_task_runner.py:77} INFO - Job 612: Subtask download_dataset_task
[2022-02-23 19:08:27,038] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [running]> on host 4709b9a36f03
[2022-02-23 19:08:27,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 19:08:27,168] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T00:00:00+00:00
[2022-02-23 19:08:27,171] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 19:08:27,174] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/output_2019-03.csv']
[2022-02-23 19:08:27,194] {subprocess.py:85} INFO - Output:
[2022-02-23 19:11:20,096] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-02-23 19:11:20,110] {subprocess.py:93} INFO - Command exited with return code 56
[2022-02-23 19:11:20,298] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-23 19:11:20,319] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190302T000000, start_date=20220223T190826, end_date=20220223T191120
[2022-02-23 19:11:20,435] {standard_task_runner.py:92} ERROR - Failed to execute job 612 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-23 19:11:20,558] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-23 19:11:20,738] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:03:31,759] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 20:03:31,789] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 20:03:31,789] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:03:31,789] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:03:31,789] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:03:31,828] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 00:00:00+00:00
[2022-02-23 20:03:31,836] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2022-02-23 20:03:31,847] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-03-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpk6xn7f0j', '--error-file', '/tmp/tmpngd99br1']
[2022-02-23 20:03:31,852] {standard_task_runner.py:77} INFO - Job 5: Subtask download_dataset_task
[2022-02-23 20:03:32,020] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [running]> on host 1bb54b80b2ee
[2022-02-23 20:03:32,099] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:03:32,149] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T00:00:00+00:00
[2022-02-23 20:03:32,150] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 20:03:32,150] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/output_2019-03.csv']
[2022-02-23 20:03:32,171] {subprocess.py:85} INFO - Output:
[2022-02-23 20:03:58,213] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-23 20:03:58,413] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190302T000000, start_date=20220223T200331, end_date=20220223T200358
[2022-02-23 20:03:58,504] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:03:58,645] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:39:42,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 20:39:42,077] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [queued]>
[2022-02-23 20:39:42,077] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:39:42,077] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:39:42,077] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:39:42,125] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-03-02 00:00:00+00:00
[2022-02-23 20:39:42,152] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-03-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpjozndfho', '--error-file', '/tmp/tmpfoa63zqy']
[2022-02-23 20:39:42,154] {standard_task_runner.py:77} INFO - Job 5: Subtask download_dataset_task
[2022-02-23 20:39:42,157] {standard_task_runner.py:52} INFO - Started process 184 to run task
[2022-02-23 20:39:42,497] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-03-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 20:39:42,709] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:39:42,793] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T00:00:00+00:00
[2022-02-23 20:39:42,794] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 20:39:42,795] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-03.csv > /opt/***/output_2019-03.csv']
[2022-02-23 20:39:42,826] {subprocess.py:85} INFO - Output:
[2022-02-23 20:39:57,253] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-23 20:39:57,289] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190302T000000, start_date=20220223T203942, end_date=20220223T203957
[2022-02-23 20:39:57,353] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:39:57,425] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
=======
>>>>>>> origin/master
