[2022-02-03 18:13:10,676] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-03 18:13:10,716] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-03 18:13:10,718] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:13:10,718] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 18:13:10,719] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:13:10,760] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 00:00:00+00:00
[2022-02-03 18:13:10,777] {standard_task_runner.py:52} INFO - Started process 783 to run task
[2022-02-03 18:13:10,781] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-02-02T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpaujnkymr', '--error-file', '/tmp/tmpx923k3ss']
[2022-02-03 18:13:10,795] {standard_task_runner.py:77} INFO - Job 144: Subtask download_dataset_task
[2022-02-03 18:13:11,452] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [running]> on host bd2f56b76e32
[2022-02-03 18:13:11,678] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 18:13:11,773] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T00:00:00+00:00
[2022-02-03 18:13:11,781] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-03 18:13:11,781] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-02.csv > /opt/***/output_2019-02.csv']
[2022-02-03 18:13:11,847] {subprocess.py:85} INFO - Output:
[2022-02-03 18:13:30,731] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-03 18:13:30,774] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190202T000000, start_date=20220203T181310, end_date=20220203T181330
[2022-02-03 18:13:30,840] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 18:13:31,128] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
<<<<<<< HEAD
[2022-02-23 19:08:26,764] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 19:08:26,782] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 19:08:26,782] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:08:26,782] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 19:08:26,782] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:08:26,807] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 00:00:00+00:00
[2022-02-23 19:08:26,814] {standard_task_runner.py:52} INFO - Started process 118 to run task
[2022-02-23 19:08:26,819] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-02-02T00:00:00+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmp48cmfq9h', '--error-file', '/tmp/tmprtqmh2z9']
[2022-02-23 19:08:26,820] {standard_task_runner.py:77} INFO - Job 614: Subtask download_dataset_task
[2022-02-23 19:08:26,947] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [running]> on host 4709b9a36f03
[2022-02-23 19:08:27,053] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 19:08:27,088] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T00:00:00+00:00
[2022-02-23 19:08:27,089] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 19:08:27,089] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-02.csv > /opt/***/output_2019-02.csv']
[2022-02-23 19:08:27,132] {subprocess.py:85} INFO - Output:
[2022-02-23 19:11:20,096] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-02-23 19:11:20,111] {subprocess.py:93} INFO - Command exited with return code 56
[2022-02-23 19:11:20,295] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-23 19:11:20,323] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190202T000000, start_date=20220223T190826, end_date=20220223T191120
[2022-02-23 19:11:20,514] {standard_task_runner.py:92} ERROR - Failed to execute job 614 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-02-23 19:11:20,575] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-23 19:11:20,812] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:03:31,758] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 20:03:31,786] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 20:03:31,786] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:03:31,787] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:03:31,787] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:03:31,807] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 00:00:00+00:00
[2022-02-23 20:03:31,814] {standard_task_runner.py:52} INFO - Started process 103 to run task
[2022-02-23 20:03:31,827] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-02-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpuvwtvwkd', '--error-file', '/tmp/tmp0bawtetz']
[2022-02-23 20:03:31,839] {standard_task_runner.py:77} INFO - Job 4: Subtask download_dataset_task
[2022-02-23 20:03:31,969] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [running]> on host 1bb54b80b2ee
[2022-02-23 20:03:32,041] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:03:32,089] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T00:00:00+00:00
[2022-02-23 20:03:32,090] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 20:03:32,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-02.csv > /opt/***/output_2019-02.csv']
[2022-02-23 20:03:32,123] {subprocess.py:85} INFO - Output:
[2022-02-23 20:03:59,174] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-23 20:03:59,209] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190202T000000, start_date=20220223T200331, end_date=20220223T200359
[2022-02-23 20:03:59,248] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:03:59,304] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:39:41,977] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 20:39:42,027] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [queued]>
[2022-02-23 20:39:42,027] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:39:42,027] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:39:42,027] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:39:42,050] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-02-02 00:00:00+00:00
[2022-02-23 20:39:42,058] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2022-02-23 20:39:42,070] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-02-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpkl8cds2p', '--error-file', '/tmp/tmp5covxavw']
[2022-02-23 20:39:42,071] {standard_task_runner.py:77} INFO - Job 3: Subtask download_dataset_task
[2022-02-23 20:39:42,281] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-02-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 20:39:42,518] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:39:42,586] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T00:00:00+00:00
[2022-02-23 20:39:42,587] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 20:39:42,596] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-02.csv > /opt/***/output_2019-02.csv']
[2022-02-23 20:39:42,687] {subprocess.py:85} INFO - Output:
[2022-02-23 20:40:10,801] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-23 20:40:10,989] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20190202T000000, start_date=20220223T203941, end_date=20220223T204010
[2022-02-23 20:40:11,097] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:40:11,194] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
=======
>>>>>>> origin/master
